version: 2.1
jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Init and Create Plan
          command: |
            cd iac/deploy
            terraform init -input=false
            terraform plan -out="replace_autoscaling.tfplan" \ 
              -replace="module.deploy_backend.aws_autoscaling_group.ec2_autoscaling" \
              -replace="module.deploy_frontend.aws_autoscaling_group.ec2_autoscaling" \
              -replace="module.deploy_frontend.aws_launch_template.ec2_template" \
              -replace="module.deploy_backend.aws_launch_template.ec2_template" 
      - persist_to_workspace:
          root: /tmp/project/iac
          paths:
            - .

  apply:
    working_directory: /tmp/iac
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: /tmp/iac
      - run:
          name: Apply Terraform Plan
          command: |
            cd /tmp/iac/deploy
            terraform apply -auto-approve replace_autoscaling.tfplan
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply